# general
mixed-port: 7890
ipv6: false
allow-lan: true
external-controller: 127.0.0.1:9090
profile:
  store-selected: true
  store-fake-ip: true

##### anchor area START #####
x-pg:
  mini-select-region: &x-pp-select-region
    type: select
    proxies:
      - 🔰 节点选择
      - 🎯 全部直连
      - ✈️ 手动选择
      - 📥 高耗流量
      - 🇭🇰 香港优选
      - 🇺🇸 美国优选
      - 🇯🇵 日本优选
      - 🇹🇼 台湾优选
      - 🇸🇬 新加坡优选
      - 🇰🇷 韩国优选

  mini-select-region-direct: &x-pp-select-region-direct
    type: select
    proxies:
      - 🎯 全部直连
      - 🔰 节点选择
      - ✈️ 手动选择
      - 📥 高耗流量
      - 🇭🇰 香港优选
      - 🇺🇸 美国优选
      - 🇯🇵 日本优选
      - 🇹🇼 台湾优选
      - 🇸🇬 新加坡优选
      - 🇰🇷 韩国优选

  mini-select-all-custom: &x-pp-select-all-custom
    type: select
    include-all: true
    exclude-filter: '(?i)^ℹ️ .+: \d.+ (KB|MB|GB|TB) \/ \d.+ (KB|MB|GB|TB).*$'

  urltest-region: &x-pp-region
    type: url-test
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    lazy: true
    include-all: true
    exclude-filter: "(?i:专用|noauto)"

##### anchor area END #####
proxy-groups:
  - name: 🔰 节点选择
    type: select
    proxies:
      - 🇺🇸 美国优选
      - 🎯 全部直连
      - ✈️ 手动选择
      - 🇭🇰 香港优选
      - 🇯🇵 日本优选
      - 🇹🇼 台湾优选
      - 🇸🇬 新加坡优选
      - 🇰🇷 韩国优选

  - name: ✈️ 手动选择
    <<: *x-pp-select-all-custom

  - name: 🍭 Google
    <<: *x-pp-select-region

  - name: Ⓜ️ Microsoft
    <<: *x-pp-select-region

  - name: ☁️ Onedrive
    <<: *x-pp-select-region-direct

  - name: 💻 Developer
    <<: *x-pp-select-region

  - name: ✨ GenAI
    <<: *x-pp-select-region

  - name: 🍎 Apple
    <<: *x-pp-select-region-direct

  - name: 🎮 Games
    <<: *x-pp-select-region-direct

  - name: 🎮 PlayStation
    <<: *x-pp-select-region-direct

  - name: 🎮 Steam
    <<: *x-pp-select-region

  - name: 🎵 Spotify
    <<: *x-pp-select-region

  - name: 🎥 Emby Providers
    <<: *x-pp-select-all-custom
    filter: "(?i:Emby)"

  - name: 🎥 Youtube
    <<: *x-pp-select-region

  - name: 💰 Finance
    <<: *x-pp-select-region

  - name: 💬 Telegram
    <<: *x-pp-select-region

  - name: 𝕏 Twitter
    <<: *x-pp-select-region

  - name: 📥 高耗流量
    <<: *x-pp-select-all-custom
    proxies:
      - 🔰 节点选择
      - 🎯 全部直连
      - ✈️ 手动选择

  - name: 📶 Speedtest
    <<: *x-pp-select-all-custom
    proxies:
      - 🎯 全部直连
      - 🔰 节点选择
      - ✈️ 手动选择

  - name: 🈲 Restricted
    <<: *x-pp-select-all-custom

  - name: 🎯 全部直连
    type: select
    hidden: true
    proxies:
      - DIRECT

  - name: 🛑 Block
    type: select
    hidden: true
    proxies:
      - REJECT

  - name: 🧹 广告拦截
    type: select
    proxies:
      - 🛑 Block
      - 🎯 全部直连
      - 🔰 节点选择

  - name: 🐟 漏网之鱼
    <<: *x-pp-select-region

  - name: 🇭🇰 香港优选
    <<: *x-pp-region
    filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇭🇰|\bHK[G]?\b|Hong.*?Kong|\bHKT\b|\bHKBN\b|\bHGC\b|\bWTT\b|\bCMI\b|[^-]港)).*$'

  - name: 🇺🇸 美国优选
    <<: *x-pp-region
    filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇺🇸|\bUS[A]?\b|America|United.*?States|美国|[^-]美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥)).*$'

  - name: 🇯🇵 日本优选
    <<: *x-pp-region
    filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇯🇵|\bJP[N]?\b|Japan|Tokyo|Osaka|Saitama|日本|东京|大阪|埼玉|[^-尼]日)).*$'

  - name: 🇹🇼 台湾优选
    <<: *x-pp-region
    filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇹🇼|\bTW[N]?\b|Taiwan|新北|彰化|\bCHT\b|台湾|[^-]台|\bHINET\b)).*$'

  - name: 🇸🇬 新加坡优选
    <<: *x-pp-region
    filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇸🇬|\bSG[P]?\b|Singapore|新加坡|狮城)).*$'

  - name: 🇰🇷 韩国优选
    <<: *x-pp-region
    filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇰🇷|\bK[O]?R\b|Korea|首尔|韩|韓)).*$'

##### anchor area START #####
x-rp:
  yaml: &x-rp-yaml
    type: http
    behavior: classical
    format: yaml
    interval: 86400
  text: &x-rp-text
    type: http
    behavior: classical
    format: text
    interval: 86400
  mrs: &x-rp-mrs
    type: http
    format: mrs
    interval: 86400
##### anchor area END #####
rule-providers:
  MyDirect:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/gz4zzxc/rule@main/Clash/list/myCN.list
  MyProxy:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/gz4zzxc/rule@main/Clash/list/foreign.list
  Ads:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-ads-all.mrs
  AdobeTelemetry:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/ignaciocastro/a-dove-is-dumb@main/pihole.txt
  Private_domain:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.mrs
  Private_ip:
    <<: *x-rp-mrs
    behavior: ipcidr
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/private.mrs
  Tracker:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/tracker.mrs
  PT:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-pt.mrs
  GenAIOverseas:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-ai-!cn.mrs
  GenAIExtra:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/GenAIExtra.list
  Bing:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/bing.mrs
  DeveloperDirect:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-dev@cn.mrs
  DeveloperOverseas:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-dev.mrs
  OneDrive:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/onedrive.mrs
  Microsoft:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/microsoft.mrs
  MicrosoftDirect:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/microsoft@cn.mrs
  Google:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/google.mrs
  AppleProxy:
    <<: *x-rp-text
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/AppleProxy/AppleProxy.list
  Apple:
    <<: *x-rp-text
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple.list
  AppleCDN:
    <<: *x-rp-text
    behavior: domain
    url: https://ruleset.skk.moe/Clash/domainset/apple_cdn.txt
  GamesDownload:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-game-platforms-download.mrs
  GamesDirect:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-games@cn.mrs
  GamesOverseas:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-games-!cn.mrs
  PlayStation:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/playstation.mrs
  Steam:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/steam.mrs
  Spotify:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/spotify.mrs
  Emby:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-emby.mrs
  YouTube:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/youtube.mrs
  Telegram:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/telegram.mrs
  Twitter:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/twitter.mrs
  Finance:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-finance.mrs
  FinanceExtra:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/FinanceExtra.list
  ProxyHighBandwidth:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/ProxyHighBandwidth.list
  Speedtest:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-speedtest.mrs
  RestrictedZones:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/gz4zzxc/rule@main/Clash/list/fallback.list
  China_domain:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cn.mrs
  Overseas_domain:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/geolocation-!cn.mrs
  China_ip:
    <<: *x-rp-mrs
    behavior: ipcidr
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/cn.mrs

rules:
  # 1. local
  - RULE-SET,Private_domain,🎯 全部直连
  - RULE-SET,Private_ip,🎯 全部直连,no-resolve
  # NTP service should always be direct
  - DST-PORT,123,🎯 全部直连

  # 2. block
  - RULE-SET,Ads,🧹 广告拦截
  - RULE-SET,AdobeTelemetry,🧹 广告拦截

  # 3. custom override
  - RULE-SET,MyDirect,🎯 全部直连
  - RULE-SET,MyProxy,🔰 节点选择

  # 4. direct
  - RULE-SET,Tracker,🎯 全部直连
  - RULE-SET,PT,🎯 全部直连
  - RULE-SET,MicrosoftDirect,🎯 全部直连
  - RULE-SET,GamesDownload,🎯 全部直连
  - RULE-SET,GamesDirect,🎯 全部直连
  - RULE-SET,DeveloperDirect,🎯 全部直连

  # 5. proxy
  - RULE-SET,ProxyHighBandwidth,📥 高耗流量
  - RULE-SET,RestrictedZones,🈲 Restricted
  - RULE-SET,Bing,🇺🇸 美国优选
  - RULE-SET,GenAIOverseas,✨ GenAI
  - RULE-SET,GenAIExtra,✨ GenAI
  - RULE-SET,OneDrive,☁️ Onedrive
  - RULE-SET,Microsoft,Ⓜ️ Microsoft
  - RULE-SET,YouTube,🎥 Youtube
  - RULE-SET,Google,🍭 Google
  - RULE-SET,AppleCDN,🎯 全部直连
  - RULE-SET,AppleProxy,🔰 节点选择
  - RULE-SET,DeveloperOverseas,💻 Developer
  - RULE-SET,Apple,🍎 Apple
  - RULE-SET,PlayStation,🎮 PlayStation
  - RULE-SET,Steam,🎮 Steam
  - RULE-SET,Emby,🎥 Emby Providers
  - RULE-SET,Spotify,🎵 Spotify
  - RULE-SET,Finance,💰 Finance
  - RULE-SET,FinanceExtra,💰 Finance
  - RULE-SET,Telegram,💬 Telegram
  - RULE-SET,Twitter,𝕏 Twitter
  - RULE-SET,Speedtest,📶 Speedtest
  - RULE-SET,GamesOverseas,🎮 Games

  # 6. final
  - RULE-SET,China_domain,🎯 全部直连
  - RULE-SET,Overseas_domain,🔰 节点选择
  - RULE-SET,China_ip,🎯 全部直连,no-resolve
  - DST-PORT,80,🐟 漏网之鱼
  - DST-PORT,443,🐟 漏网之鱼
  - DST-PORT,853,🐟 漏网之鱼
  - MATCH,DIRECT
