# general
mixed-port: 7890
ipv6: false
allow-lan: true
external-controller: 127.0.0.1:9090
profile:
  store-selected: true
  store-fake-ip: true

##### anchor area START #####
x-pg:
  # full-select-region: &x-pp-select-region
  #   type: select
  #   proxies:
  #     - 🔰 节点选择
  #     - 🎯 全部直连
  #     - 📥 高耗流量
  #     - ✈️ 手动选择
  #     - 🎩 私有节点
  #     - 🏠 家宽节点
  #     - 🇭🇰 香港优选
  #     - 🇺🇸 美国优选
  #     - 🇯🇵 日本优选
  #     - 🇹🇼 台湾优选
  #     - 🇸🇬 新加坡优选
  #     - 🇰🇷 韩国优选
  #     - 🇮🇳 印度优选
  #     - 🇬🇧 英国优选
  #     - 🇫🇷 法国优选
  #     - 🇨🇦 加拿大优选
  #     - 🇦🇺 澳大利亚优选
  #     - 🇷🇺 俄罗斯优选
  #     - 🇹🇷 土耳其优选
  #     - 🇦🇷 阿根廷优选
  #     - 🇧🇷 巴西优选
  #     # - 🇨🇳 回国选择

  # full-select-region-direct: &x-pp-select-region-direct
  #   type: select
  #   proxies:
  #     - 🎯 全部直连
  #     - 🔰 节点选择
  #     - 📥 高耗流量
  #     - ✈️ 手动选择
  #     - 🎩 私有节点
  #     - 🏠 家宽节点
  #     - 🇭🇰 香港优选
  #     - 🇺🇸 美国优选
  #     - 🇯🇵 日本优选
  #     - 🇹🇼 台湾优选
  #     - 🇸🇬 新加坡优选
  #     - 🇰🇷 韩国优选
  #     - 🇮🇳 印度优选
  #     - 🇬🇧 英国优选
  #     - 🇫🇷 法国优选
  #     - 🇨🇦 加拿大优选
  #     - 🇦🇺 澳大利亚优选
  #     - 🇷🇺 俄罗斯优选
  #     - 🇹🇷 土耳其优选
  #     - 🇦🇷 阿根廷优选
  #     - 🇧🇷 巴西优选
  #     # - 🇨🇳 回国选择

  mini-select-region: &x-pp-select-region
    type: select
    proxies:
      - 🔰 节点选择
      - 🎯 全部直连
      - ✈️ 手动选择
      - 🎩 私有节点
      # - 🏠 家宽节点
      - 📥 高耗流量
      - 🇭🇰 香港优选
      - 🇺🇸 美国优选
      - 🇯🇵 日本优选
      - 🇹🇼 台湾优选
      - 🇸🇬 新加坡优选
      - 🇰🇷 韩国优选

  mini-select-region-direct: &x-pp-select-region-direct
    type: select
    proxies:
      - 🎯 全部直连
      - 🔰 节点选择
      - ✈️ 手动选择
      - 🎩 私有节点
      # - 🏠 家宽节点
      - 📥 高耗流量
      - 🇭🇰 香港优选
      - 🇺🇸 美国优选
      - 🇯🇵 日本优选
      - 🇹🇼 台湾优选
      - 🇸🇬 新加坡优选
      - 🇰🇷 韩国优选

  mini-select-region-private: &x-pp-select-region-private
    type: select
    proxies:
      - 🎩 私有节点
      - 🔰 节点选择
      - 🎯 全部直连
      - ✈️ 手动选择
      # - 🏠 家宽节点
      - 📥 高耗流量
      - 🇭🇰 香港优选
      - 🇺🇸 美国优选
      - 🇯🇵 日本优选
      - 🇹🇼 台湾优选
      - 🇸🇬 新加坡优选
      - 🇰🇷 韩国优选

  mini-select-region-clean: &x-pp-select-region-clean
    type: select
    proxies:
      # - 🏠 家宽节点
      - 🔰 节点选择
      - 🎯 全部直连
      - ✈️ 手动选择
      - 🎩 私有节点
      - 📥 高耗流量
      - 🇭🇰 香港优选
      - 🇺🇸 美国优选
      - 🇯🇵 日本优选
      - 🇹🇼 台湾优选
      - 🇸🇬 新加坡优选
      - 🇰🇷 韩国优选

  mini-select-all-custom: &x-pp-select-all-custom
    type: select
    include-all: true
    exclude-filter: '(?i)^ℹ️ .+: \d.+ (KB|MB|GB|TB) \/ \d.+ (KB|MB|GB|TB).*$'

  urltest-region: &x-pp-region
    type: url-test
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    lazy: true
    include-all: true
    # hidden: true
    exclude-filter: "(?i:专用|noauto)"

  # select-region: &x-pp-region
  #   type: select
  #   include-all: true
  #   hidden: true

##### anchor area END #####
proxy-groups:
  ## control groups
  - name: ℹ️ 订阅信息
    type: select
    include-all: true
    filter: '(?i)^ℹ️ .+: \d.+ (KB|MB|GB|TB) \/ \d.+ (KB|MB|GB|TB).*$'

  - name: 🔰 节点选择
    type: select
    proxies:
      - ✈️ 手动选择
      - 🎯 全部直连
      - 🎩 私有节点
      # - 🏠 家宽节点
      - 🇭🇰 香港优选
      - 🇺🇸 美国优选
      - 🇯🇵 日本优选
      - 🇹🇼 台湾优选
      - 🇸🇬 新加坡优选
      - 🇰🇷 韩国优选
      # - 🇮🇳 印度优选
      # - 🇬🇧 英国优选
      # - 🇫🇷 法国优选
      # - 🇨🇦 加拿大优选
      # - 🇦🇺 澳大利亚优选
      # - 🇷🇺 俄罗斯优选
      # - 🇹🇷 土耳其优选
      # - 🇦🇷 阿根廷优选
      # - 🇧🇷 巴西优选
      # - 🇨🇳 回国选择

  - name: ✈️ 手动选择
    <<: *x-pp-select-all-custom

  - name: 🎩 私有节点
    <<: *x-pp-select-all-custom
    filter: "(?i:Private|PRIV)"

#   - name: 🏠 家宽节点
#     <<: *x-pp-select-all-custom
#     filter: "(?i:家宽|Clean)"

  - name: 📥 高耗流量
    <<: *x-pp-select-all-custom
    proxies:
      - 🔰 节点选择
      - 🎯 全部直连
      - ✈️ 手动选择
      - 🎩 私有节点
      # - 🏠 家宽节点

  - name: 📶 Speedtest
    <<: *x-pp-select-all-custom
    proxies:
      - 🎯 全部直连
      - 🔰 节点选择
      - ✈️ 手动选择
      - 🎩 私有节点
      # - 🏠 家宽节点
      - 📥 高耗流量

  - name: 🐟 漏网之鱼
    <<: *x-pp-select-region

  - name: 🎯 全部直连
    type: select
    hidden: true
    proxies:
      - DIRECT

  - name: 🛑 Block
    type: select
    hidden: true
    proxies:
      - REJECT

  - name: 🧹 广告拦截
    type: select
    proxies:
      - 🛑 Block
      - 🎯 全部直连
      - 🔰 节点选择

  ## services groups
  - name: 🍎 Apple
    <<: *x-pp-select-region-direct

  - name: 🍭 Google
    <<: *x-pp-select-region

  - name: Ⓜ️ Microsoft
    <<: *x-pp-select-region

  - name: ☁️ Onedrive
    <<: *x-pp-select-region-direct

  - name: 💻 Developer
    <<: *x-pp-select-region

  - name: ✨ GenAI
    <<: *x-pp-select-region

  - name: 🎮 Games
    <<: *x-pp-select-region-direct

  - name: 🎮 Nintendo
    <<: *x-pp-select-region-direct

  - name: 🎮 PlayStation
    <<: *x-pp-select-region-direct

  - name: 🎮 Steam
    <<: *x-pp-select-region

  - name: 🎵 Spotify
    <<: *x-pp-select-region

  - name: 🎵 Qobuz
    <<: *x-pp-select-region

  - name: 🎥 Emby Providers
    <<: *x-pp-select-all-custom
    filter: "(?i:Emby)"

  - name: 🎥 Youtube
    <<: *x-pp-select-region

  - name: 🎥 Netflix
    <<: *x-pp-select-region

  - name: 🎥 Apple TV
    <<: *x-pp-select-region

  - name: 🎥 TikTok
    <<: *x-pp-select-region

  - name: 💰 Finance
    <<: *x-pp-select-region

  - name: 💬 Telegram
    <<: *x-pp-select-region

  - name: 𝕏 Twitter
    <<: *x-pp-select-region

  - name: 💰 Crypto
    <<: *x-pp-select-region

  - name: 💰 Banking@HK
    <<: *x-pp-select-region

  - name: 🈲 Restricted
    <<: *x-pp-select-all-custom

  ## region groups
  - name: 🇭🇰 香港优选
    <<: *x-pp-region
    filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇭🇰|\bHK[G]?\b|Hong.*?Kong|\bHKT\b|\bHKBN\b|\bHGC\b|\bWTT\b|\bCMI\b|[^-]港)).*$'

  - name: 🇺🇸 美国优选
    <<: *x-pp-region
    filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇺🇸|\bUS[A]?\b|America|United.*?States|美国|[^-]美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥)).*$'

  - name: 🇯🇵 日本优选
    <<: *x-pp-region
    filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇯🇵|\bJP[N]?\b|Japan|Tokyo|Osaka|Saitama|日本|东京|大阪|埼玉|[^-尼]日)).*$'

  - name: 🇹🇼 台湾优选
    <<: *x-pp-region
    filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇹🇼|\bTW[N]?\b|Taiwan|新北|彰化|\bCHT\b|台湾|[^-]台|\bHINET\b)).*$'

  - name: 🇸🇬 新加坡优选
    <<: *x-pp-region
    filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇸🇬|\bSG[P]?\b|Singapore|新加坡|狮城)).*$'

  - name: 🇰🇷 韩国优选
    <<: *x-pp-region
    filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇰🇷|\bK[O]?R\b|Korea|首尔|韩|韓)).*$'

  # - name: 🇮🇳 印度优选
  #   <<: *x-pp-region
  #   filter: '(?i:🇮🇳|\bIN[D]?\b|India|Mumbai|印度|孟买)'

  # - name: 🇬🇧 英国优选
  #   <<: *x-pp-region
  #   filter: '(?i:🇬🇧|\bUK\b|England|United.*?Kingdom|London|英国|[^-]英|伦敦)'

  # - name: 🇫🇷 法国优选
  #   <<: *x-pp-region
  #   filter: '(?i:🇫🇷|\bFR[A]?\b|France|Paris|法国|巴黎)'

  # - name: 🇨🇦 加拿大优选
  #   <<: *x-pp-region
  #   filter: '(?i:🇨🇦|\bCA[N]?\b|Canada|Toronto|Montreal|加拿大|多伦多|蒙特利尔)'

  # - name: 🇦🇺 澳大利亚优选
  #   <<: *x-pp-region
  #   filter: '(?i:🇦🇺|\bAU[S]?\b|Australia|Sydney|澳大利亚|澳洲|悉尼)'

  # - name: 🇷🇺 俄罗斯优选
  #   <<: *x-pp-region
  #   filter: '(?i:🇷🇺|\bRU[S]?\b|Russia|Moscow|俄罗斯|莫斯科)'

  # - name: 🇹🇷 土耳其优选
  #   <<: *x-pp-region
  #   filter: "(?i:🇹🇷|Turkey|土耳其|伊斯坦布尔)"

  # - name: 🇦🇷 阿根廷优选
  #   <<: *x-pp-region
  #   filter: '(?i:🇦🇷|\bAR[G]?\b|Argentina|Buenos.*?Aires|阿根廷|布宜诺斯艾利斯)'

  # - name: 🇧🇷 巴西优选
  #   <<: *x-pp-region
  #   filter: '(?i:🇧🇷|\bBR[A]?\b|Brazil|São.*?Paulo|Rio.*?de.*?Janeiro|巴西|圣保罗|里约热内卢)'

  # - name: 🇨🇳 回国选择
  #   type: select
  #   include-all: true
  #   hidden: true
  #   filter: '(?i:\bC[H]?N\b|China|回国|中国[^-]|江苏[^-]|北京[^-]|上海[^-]|广州[^-]|深圳[^-]|杭州[^-]|常州[^-]|徐州[^-]|青岛[^-]|宁波[^-]|镇江[^-]|成都[^-]|back)'

##### anchor area START #####
x-rp:
  yaml: &x-rp-yaml
    type: http
    behavior: classical
    format: yaml
    interval: 86400
  text: &x-rp-text
    type: http
    behavior: classical
    format: text
    interval: 86400
  mrs: &x-rp-mrs
    type: http
    format: mrs
    interval: 86400
##### anchor area END #####
rule-providers:
  # 1. local
  Private_domain:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.mrs
  Private_ip:
    <<: *x-rp-mrs
    behavior: ipcidr
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/private.mrs

  # 2. block
  Ads:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-ads-all.mrs
  AdobeTelemetry:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/ignaciocastro/a-dove-is-dumb@main/pihole.txt

  # 3. custom override
  MyDirect:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/gz4zzxc/rule@main/Clash/list/myCN.list
  MyProxy:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/gz4zzxc/rule@main/Clash/list/foreign.list

  # 4. main: p1
  TailscaleDERP_domain:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/TailscaleDERP_domain.list
  TailscaleDERP_ip:
    <<: *x-rp-text
    behavior: ipcidr
    url: https://fastly.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/TailscaleDERP_ip.list
  Tailscale_domain:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/Tailscale_domain.list
  Tailscale_ip:
    <<: *x-rp-text
    behavior: ipcidr
    url: https://fastly.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/Tailscale_ip.list
  Tracker:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/tracker.mrs
  PT:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-pt.mrs
  Speedtest:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-speedtest.mrs
  ProxyHighBandwidth:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/ProxyHighBandwidth.list

  # 5. main: p2
  Bing:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/bing.mrs
  OneDrive:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/onedrive.mrs
  GoogleVoice:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/GoogleVoice.list
  Telegram_domain:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/telegram.mrs
  Telegram_ip:
    <<: *x-rp-mrs
    behavior: ipcidr
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/telegram.mrs
  Twitter_domain:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/twitter.mrs
  Twitter_ip:
    <<: *x-rp-mrs
    behavior: ipcidr
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/twitter.mrs
  Nintendo:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/nintendo.mrs
  PlayStation:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/playstation.mrs
  Steam:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/steam.mrs
  YouTube:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/youtube.mrs
  Netflix_domain:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/netflix.mrs
  Netflix_ip:
    <<: *x-rp-mrs
    behavior: ipcidr
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/netflix.mrs
  AppleTV:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/apple-tvplus.mrs
  Bahamut:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/bahamut.mrs
  TikTok:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/tiktok.mrs
  Emby:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-emby.mrs
  Spotify:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/spotify.mrs
  Qobuz:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/Qobuz.list

  # 6. main: p3
  RestrictedZones:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/gz4zzxc/rule@main/Clash/list/fallback.list
  GamesDownload:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-game-platforms-download.mrs
  GamesDirect:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-games@cn.mrs
  GamesOverseas:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-games-!cn.mrs
  DeveloperDirect:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-dev@cn.mrs
  DeveloperOverseas:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-dev.mrs
  GenAIOverseas:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-ai-!cn.mrs
  GenAIExtra:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/GenAIExtra.list
  Crypto:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-cryptocurrency.mrs
  CryptoExtra:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/CryptoExtra.list
  Finance:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-finance.mrs
  FinanceExtra:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/FinanceExtra.list
  HongKongBank:
    <<: *x-rp-text
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/gz4zzxc/rule@main/Clash/rule/HongKongBank.list

  # 7. main: p4
  MicrosoftDirect:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/microsoft@cn.mrs
  Microsoft:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/microsoft.mrs
  Google_domain:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/google.mrs
  Google_ip:
    <<: *x-rp-mrs
    behavior: ipcidr
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/google.mrs
  AppleProxy:
    # TODO: switch to mrs + domain behavior
    <<: *x-rp-text
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/AppleProxy/AppleProxy.list
  Apple:
    # TODO: switch to mrs + domain behavior
    <<: *x-rp-text
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple.list
  AppleCDN:
    <<: *x-rp-text
    behavior: domain
    url: https://ruleset.skk.moe/Clash/domainset/apple_cdn.txt

  China_domain:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cn.mrs
  Overseas_domain:
    <<: *x-rp-mrs
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/geolocation-!cn.mrs
  China_ip:
    <<: *x-rp-mrs
    behavior: ipcidr
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/cn.mrs

rules:
  # domain > classical > ipcidr
  # 1. local
  - RULE-SET,Private_domain,🎯 全部直连
  - RULE-SET,Private_ip,🎯 全部直连,no-resolve
  # NTP service should always be direct
  - DST-PORT,123,🎯 全部直连

  # 2. block
  - RULE-SET,Ads,🧹 广告拦截
  - RULE-SET,AdobeTelemetry,🧹 广告拦截

  # 3. custom override
  - RULE-SET,MyDirect,🎯 全部直连
  - RULE-SET,MyProxy,🔰 节点选择

  # 4. main: p1
  - RULE-SET,TailscaleDERP_domain,🎯 全部直连
  - RULE-SET,Tailscale_domain,🎯 全部直连
  - RULE-SET,TailscaleDERP_ip,🎯 全部直连,no-resolve
  - RULE-SET,Tailscale_ip,🎯 全部直连,no-resolve
  - RULE-SET,Tracker,🎯 全部直连
  - RULE-SET,PT,🎯 全部直连
  - RULE-SET,Speedtest,📶 Speedtest
  - RULE-SET,ProxyHighBandwidth,📥 高耗流量

  # 5. main: p2
  - RULE-SET,Bing,🇺🇸 美国优选
  - RULE-SET,OneDrive,☁️ Onedrive
  - RULE-SET,GoogleVoice,🇺🇸 美国优选
  - RULE-SET,Telegram_domain,💬 Telegram
  - RULE-SET,Telegram_ip,💬 Telegram,no-resolve
  - RULE-SET,Twitter_domain,𝕏 Twitter
  - RULE-SET,Twitter_ip,𝕏 Twitter,no-resolve
  - RULE-SET,Nintendo,🎮 Nintendo
  - RULE-SET,PlayStation,🎮 PlayStation
  - RULE-SET,Steam,🎮 Steam
  - RULE-SET,YouTube,🎥 Youtube
  - RULE-SET,Netflix_domain,🎥 Netflix
  - RULE-SET,Netflix_ip,🎥 Netflix,no-resolve
  - RULE-SET,AppleTV,🎥 Apple TV
  - RULE-SET,Bahamut,🇹🇼 台湾优选
  - RULE-SET,TikTok,🎥 TikTok
  - RULE-SET,Emby,🎥 Emby Providers
  - RULE-SET,Spotify,🎵 Spotify
  - RULE-SET,Qobuz,🎵 Qobuz

  # 6. main: p3
  - RULE-SET,RestrictedZones,🈲 Restricted
  - RULE-SET,GamesDownload,🎯 全部直连
  - RULE-SET,GamesDirect,🎯 全部直连
  - RULE-SET,DeveloperDirect,🎯 全部直连
  - RULE-SET,MicrosoftDirect,🎯 全部直连
  - RULE-SET,GamesOverseas,🎮 Games
  - RULE-SET,DeveloperOverseas,💻 Developer
  - RULE-SET,GenAIOverseas,✨ GenAI
  - RULE-SET,GenAIExtra,✨ GenAI
  - RULE-SET,Crypto,💰 Crypto
  - RULE-SET,CryptoExtra,💰 Crypto
  - RULE-SET,Finance,💰 Finance
  - RULE-SET,FinanceExtra,💰 Finance
  - RULE-SET,HongKongBank,💰 Banking@HK

  # 7. main: p4
  - RULE-SET,Microsoft,Ⓜ️ Microsoft
  - RULE-SET,Google_domain,🍭 Google
  - RULE-SET,Google_ip,🍭 Google,no-resolve
  - RULE-SET,AppleCDN,🎯 全部直连
  - RULE-SET,AppleProxy,🔰 节点选择
  - RULE-SET,Apple,🍎 Apple

  # 8. final
  - RULE-SET,China_domain,🎯 全部直连
  - RULE-SET,Overseas_domain,🔰 节点选择
  - RULE-SET,China_ip,🎯 全部直连,no-resolve
  - DST-PORT,80,🐟 漏网之鱼
  - DST-PORT,443,🐟 漏网之鱼
  - DST-PORT,853,🐟 漏网之鱼
  - MATCH,DIRECT
